Repository ouzi-dev/test-infra, pull requests merged in 2019-10, with the labels that each got.

#12 feat: put an oauth proxy behind deck
  infrastructure/main.tf
  infrastructure/outputs.tf
  infrastructure/templates/_prow_values.yaml
  infrastructure/terraform.tfvars
  infrastructure/variables.tf
  prow/README.md
  prow/cluster/05-oauth/manifests/resources.yaml
  prow/manifests/03-starter.yaml
Labels: approved, lgtm, size/M, ¯\_(ツ)_/¯

#14 Feat/make infra generic
  infrastructure/Makefile
  infrastructure/main.tf
  infrastructure/outputs.tf
  infrastructure/terraform.tfvars
  infrastructure/variables.tf
Labels: approved, lgtm, size/S

#16 Remove need to specify zones - make them always three
  infrastructure/main.tf
  infrastructure/terraform.tfvars
  infrastructure/variables.tf
Labels: approved, lgtm, size/S

#17 feature: added jobs for avro-kedavro and use the correct images for w…
  README.md
  config/jobs/ouzi-dev/avro-kedavro/avro-kedavro-jobs.yaml
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/M

#18 fix: removed branches cause it looks it doesn't trigger jobs correctly
  config/jobs/ouzi-dev/avro-kedavro/avro-kedavro-jobs.yaml
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/XS

#19 fix: use correct github token for semantic-release
  config/jobs/ouzi-dev/avro-kedavro/avro-kedavro-jobs.yaml
Labels: approved, lgtm, size/XS

#20 Add new preset for semantic release
  config/jobs/ouzi-dev/gke-terraform/gke-terraform-jobs.yaml
  config/jobs/ouzi-dev/prow-gke-terraform/prow-gke-terraform-jobs.yaml
  prow/config.yaml
  prow/templates/config.yaml.template
Labels: approved, lgtm, size/M

#21 Feat/switch to prow tf module
  infrastructure/main.tf
  infrastructure/outputs.tf
  infrastructure/templates/_prow_github_oauth_config.yaml
  infrastructure/templates/_prow_values.yaml
  infrastructure/terraform.tfvars
  infrastructure/variables.tf
  infrastructure/versions.tf
  prow/manifests/00-init.yaml
Labels: approved, lgtm, size/XL

#23 Add helm image job
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/S, ¯\_(ツ)_/¯

#22 add prow helm chart jobs
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts-jobs.yaml
  prow/config.yaml
  prow/templates/config.yaml.template
Labels: approved, lgtm, size/M

#24 Fix repo name for prow-helm-chart
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts-jobs.yaml
Labels: approved, lgtm, size/XS

#25 feat: Add postsubmit semver job for bigbang repo
  config/jobs/ouzi-dev/bigbang/bigbang-jobs.yaml
Labels: approved, lgtm, size/S

#26 fix: use image with helm when doing the release
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts-jobs.yaml
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/S

#27 fix: add package and semrelease dry run jobs
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts-jobs.yaml
Labels: approved, lgtm, size/M

#28 fix: add needed creds for the job
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts-jobs.yaml
Labels: approved, lgtm, size/XS

#29 feat: Add Helm Admin SA when releasing helm charts
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts-jobs.yaml
  prow/config.yaml
  prow/templates/config.yaml.template
Labels: approved, lgtm, size/S

#30 Fix/switch to helmv2
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts-jobs.yaml
Labels: approved, lgtm, size/S

#32 fix: added colour for released label
  prow/labels.yaml
Labels: approved, lgtm, size/XS

#34 fix: use just one oauth proxy for the whole subdomain
  prow/Makefile
  prow/cluster/05-oauth/manifests/resources.yaml
  prow/manifests/03-starter.yaml
  prow/templates/labels.yaml.template
Labels: approved, lgtm, size/M

#35 feat: add grafana and dashboards
  config/jobs/ouzi-dev/test-infra/jobs.yaml
  monitoring/Makefile
  monitoring/README.md
  monitoring/grafana-dashboards/dashboards.jsonnet
  monitoring/grafana-dashboards/output/deck-dashboard.json
  monitoring/grafana-dashboards/output/ghproxy-dashboard.json
  monitoring/grafana-dashboards/output/hook-dashboard.json
  monitoring/grafana-dashboards/output/mixin-cluster-total.json
  monitoring/grafana-dashboards/output/mixin-k8s-resources-cluster.json
  monitoring/grafana-dashboards/output/mixin-k8s-resources-namespace.json
  monitoring/grafana-dashboards/output/mixin-k8s-resources-node.json
  monitoring/grafana-dashboards/output/mixin-k8s-resources-pod.json
  monitoring/grafana-dashboards/output/mixin-k8s-resources-workload.json
  monitoring/grafana-dashboards/output/mixin-k8s-resources-workloads-namespace.json
  monitoring/grafana-dashboards/output/mixin-kubelet.json
  monitoring/grafana-dashboards/output/mixin-namespace-by-pod.json
  monitoring/grafana-dashboards/output/mixin-namespace-by-workload.json
  monitoring/grafana-dashboards/output/mixin-persistentvolumesusage.json
  monitoring/grafana-dashboards/output/mixin-pod-total.json
  monitoring/grafana-dashboards/output/mixin-pods.json
  monitoring/grafana-dashboards/output/mixin-statefulset.json
  monitoring/grafana-dashboards/output/mixin-workload-total.json
  monitoring/grafana-dashboards/output/plank-dashboard.json
  monitoring/grafana-dashboards/output/prow-dashboard.json
  monitoring/grafana-dashboards/output/sinker-dashboard.json
  monitoring/grafana-dashboards/output/tide-dashboard.json
  monitoring/grafana-dashboards/output/values.json
  monitoring/grafana-dashboards/raw/nginx-ingress-controller.json
  monitoring/grafana/values.yaml
  monitoring/jsonnetfile.json
  monitoring/jsonnetfile.lock.json
  monitoring/kube-prometheus/additional-rbac.libsonnet
  monitoring/kube-prometheus/ingress.libsonnet
  monitoring/kube-prometheus/kube-prometheus.jsonnet
  monitoring/kube-prometheus/managed-gke.libsonnet
  monitoring/manifests/prometheus/prometheus-clusterRole.yaml
  monitoring/manifests/prometheus/prometheus-rules.yaml
  monitoring/manifests/service-monitors/nginx-ingress-controller.yaml
  prow/cluster/03-nginx-ingress/helm/values.yaml
  prow/config.yaml
  prow/manifests/03-starter.yaml
  prow/templates/config.yaml.template
Labels: approved, lgtm, size/XXL
