Repository ouzi-dev/test-infra, pull requests merged in 2019-11, with the labels that each got.

#36 fix: fix grafana dashboards path in github to use master branch
  monitoring/grafana-dashboards/dashboards.jsonnet
  monitoring/grafana-dashboards/output/values.json
Labels: approved, lgtm, size/M

#38 fix: add resources to docker build
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/S

#39 fix: update prometheus
  monitoring/grafana-dashboards/output/mixin-cluster-total.json
  monitoring/grafana-dashboards/output/mixin-namespace-by-pod.json
  monitoring/grafana-dashboards/output/mixin-namespace-by-workload.json
  monitoring/jsonnetfile.lock.json
  monitoring/manifests/prometheus/01-prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
  monitoring/manifests/prometheus/01-prometheus-operator-0podmonitorCustomResourceDefinition.yaml
  monitoring/manifests/prometheus/01-prometheus-operator-0prometheusCustomResourceDefinition.yaml
  monitoring/manifests/prometheus/01-prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
  monitoring/manifests/prometheus/01-prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
  monitoring/manifests/prometheus/01-prometheus-operator-clusterRole.yaml
  monitoring/manifests/prometheus/01-prometheus-operator-clusterRoleBinding.yaml
  monitoring/manifests/prometheus/01-prometheus-operator-deployment.yaml
  monitoring/manifests/prometheus/01-prometheus-operator-service.yaml
  monitoring/manifests/prometheus/01-prometheus-operator-serviceAccount.yaml
  monitoring/manifests/prometheus/prometheus-operator-serviceMonitor.yaml
Labels: approved, lgtm, size/XXL

#37 Feat/add cannon prow jobs
  config/jobs/ouzi-dev/cannon-prow/cannon-prow-jobs.yaml
  config/jobs/ouzi-dev/test-infra/test-infra-jobs.yaml
  prow/config.yaml
  prow/job.yaml
  prow/manifests/00-init.yaml
  prow/plugins.yaml
  prow/templates/config.yaml.template
Labels: approved, lgtm, size/L

#40 fix auto approve
  config/jobs/ouzi-dev/cannon-prow/cannon-prow-jobs.yaml
Labels: approved, lgtm, size/XS

#41 feat: update checkconfig for the ouzi test-infra to the version of prow
  config/jobs/ouzi-dev/test-infra/test-infra-jobs.yaml
Labels: approved, lgtm, size/XS

#42 feat: use credstash to store secrets from tf
  infrastructure/.gitignore
  infrastructure/.kubeconfig.yaml.tpl
  infrastructure/Makefile
  infrastructure/outputs.tf
Labels: approved, lgtm, size/L

#43 fix: export all secrets from tf to credstash
  infrastructure/.gitignore
  infrastructure/Makefile
Labels: approved, lgtm, size/S

#45 fix: run postsubmit only on master
  config/jobs/ouzi-dev/cannon-prow/cannon-prow-jobs.yaml
Labels: approved, lgtm, size/XS

#46 fix: trigger reload of jobs
  config/jobs/ouzi-dev/test-infra/test-infra-jobs.yaml
Labels: approved, lgtm, size/XS

#47 fix: trigger reload of jobs
  config/jobs/ouzi-dev/avro-kedavro/avro-kedavro-jobs.yaml
  config/jobs/ouzi-dev/bigbang/bigbang-jobs.yaml
  config/jobs/ouzi-dev/cannon-prow/cannon-prow-jobs.yaml
  config/jobs/ouzi-dev/gke-terraform/gke-terraform-jobs.yaml
  config/jobs/ouzi-dev/prow-gke-terraform/prow-gke-terraform-jobs.yaml
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts-jobs.yaml
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/S

#48 fix: add dockerconfig
  cluster/values.yaml
Labels: approved, lgtm, size/XS

#50 feat: fix rbac for deployments
  Makefile
  cluster/08-prow/manifests/pre/03-serviceaccount.yaml
Labels: approved, lgtm, size/M

#49 fix: use correct annotation for ssl-redirect
  cluster/05-oauth-proxy/manifests/pre/06-ingress.yaml
  config/jobs/ouzi-dev/test-infra/test-infra-jobs.yaml
  monitoring/Makefile
  monitoring/grafana/values.yaml
  monitoring/manifests/expose/alertmanager-ingress.yaml
  monitoring/manifests/expose/prometheus-ingress.yaml
  prow/plugins.yaml
Labels: approved, lgtm, size/S

#52 fix: remove unused label
  Makefile
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts-jobs.yaml
  prow/config.yaml
Labels: approved, lgtm, size/S

#53 fix: bump prow helm chart version
  cluster/Makefile
Labels: approved, lgtm, size/XS

#51 Feat: fix tide config to check all contexts
  Makefile
  prow/config.yaml
Labels: approved, lgtm, size/L

#54 feat: auto deploy cluster on merge
  Makefile
  cluster/Makefile
  cluster/values.yaml
  config/jobs/ouzi-dev/test-infra/test-infra-jobs.yaml
  infrastructure/Makefile
  infrastructure/main.tf
  prow/config.yaml
Labels: approved, lgtm, size/L

#55 fix: upgrade to latest prow tf module
  infrastructure/main.tf
Labels: approved, lgtm, size/XS

#56 feat: add tolerations to whallers of the moon jobs
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
  infrastructure/main.tf
Labels: approved, lgtm, size/M
