Repository ouzi-dev/test-infra, pull requests merged in 2020-02, with the labels that each got.

#60 feat: bump to latest prow v0.5.0
  cluster/Makefile
Labels: approved, lgtm, size/XS

#61 feat: bump to latest prow v0.5.1
  cluster/Makefile
Labels: approved, lgtm, size/XS

#62 feat: enable in repo config
  Makefile
  config/jobs/ouzi-dev/ouzi-dev.yaml
  config/jobs/ouzi-dev/test-infra/test-infra-jobs.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#63 fix: enable for all repos
  config/jobs/ouzi-dev/ouzi-dev.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#64 feat: bump prow helm chart to v0.6.0
  cluster/Makefile
Labels: approved, lgtm, size/XS

#65 fix: rename jobs
  config/jobs/ouzi-dev/test-infra/test-infra-jobs.yaml
Labels: approved, lgtm, size/S

#66 fix: update to helm chart 0.6.4
  cluster/Makefile
Labels: approved, lgtm, size/XS

#67 fix: enable lenses in spyglass
  cluster/Makefile
  prow/config.yaml
Labels: approved, lgtm, size/M

#68 fix: add org in job url
  prow/config.yaml
Labels: approved, lgtm, size/XS

#69 fix: update job url from k8s testinfra
  prow/config.yaml
Labels: approved, lgtm, size/XS

#70 feat: add new credstash operator
  cluster/03-credstash-controller/manifests/pre/00-crd.yaml
  cluster/03-credstash-controller/manifests/pre/01-rbac.yaml
  cluster/03-credstash-controller/manifests/pre/02-aws-secrets.yaml
  cluster/03-credstash-controller/manifests/pre/03-deployment.yaml
  cluster/03-credstash-controller/manifests_values.yaml.tpl
  cluster/04-cert-manager/manifests/post/02-clouddns-dns01-solver-svc-acct.yaml
  cluster/05-oauth-proxy/manifests/pre/02-secret.yaml
  cluster/08-prow/manifests/pre/02-credstashsecret.yaml
  cluster/09-build-secrets/manifests/pre/00-credstashsecret.yaml
  cluster/10-credstash-operator/helm_values.yaml.tpl
  cluster/10-credstash-operator/manifests/pre/01-namespace.yaml
  cluster/10-credstash-operator/manifests_values.yaml.tpl
  cluster/Makefile
  cluster/values.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#71 feat: add git secret scanner job
  config/jobs/ouzi-dev/ouzi-dev.yaml
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/M

#72 feat: run on all repos
  config/jobs/ouzi-dev/ouzi-dev.yaml
Labels: approved, lgtm, size/XS

#73 feat: add nocreds check
  config/jobs/ouzi-dev/avro-kedavro/avro-kedavro-jobs.yaml
  config/jobs/ouzi-dev/bigbang/bigbang-jobs.yaml
  config/jobs/ouzi-dev/cannon-prow/cannon-prow-jobs.yaml
  config/jobs/ouzi-dev/credstash-operator/credstash_operator.yaml
  config/jobs/ouzi-dev/gke-terraform/gke-terraform-jobs.yaml
  config/jobs/ouzi-dev/ouzi-dev.yaml
  config/jobs/ouzi-dev/prow-gke-terraform/prow-gke-terraform-jobs.yaml
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts-jobs.yaml
  config/jobs/ouzi-dev/test-infra/test-infra-jobs.yaml
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/L

#74 feat: add ouzi.io under management
  config/jobs/ouzi-dev/ouzi.io/ouzi-io.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#75 feat: add missing repos
  config/jobs/ouzi-dev/avro-kedavro/avro-kedavro.yaml
  config/jobs/ouzi-dev/bigbang/bigbang.yaml
  config/jobs/ouzi-dev/cannon-prow/cannon-prow.yaml
  config/jobs/ouzi-dev/commit-status-updater/commit-status-updater.yaml
  config/jobs/ouzi-dev/dind-action/dind-action.yaml
  config/jobs/ouzi-dev/docs/docs.yaml
  config/jobs/ouzi-dev/eks-terraform/eks-terraform.yaml
  config/jobs/ouzi-dev/gke-terraform/gke-terraform.yaml
  config/jobs/ouzi-dev/go-make-action/go-make-action.yaml
  config/jobs/ouzi-dev/owners-template/owners-template.yaml
  config/jobs/ouzi-dev/prow-gke-terraform/prow-gke-terraform.yaml
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts.yaml
  config/jobs/ouzi-dev/syrinx/syrinx.yaml
  config/jobs/ouzi-dev/test-infra/test-infra.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#76 bump: toolbox version
  config/jobs/ouzi-dev/cannon-prow/cannon-prow.yaml
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts.yaml
  config/jobs/ouzi-dev/test-infra/test-infra.yaml
Labels: approved, lgtm, size/S

#77 feat: add hoarder prow under prow management
  config/jobs/ouzi-dev/hoarder-prow/hoarder-prow.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#78 feat: bootstrap hoarder prow
  cluster/values.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#79 feat: add new image to whalers of the moon builds
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/M

#80 feat: remove jobs that are now in the WotM repo
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/L

#81 fix: use correct checkconfig
  Makefile
  config/jobs/ouzi-dev/avro-kedavro/avro-kedavro.yaml
  config/jobs/ouzi-dev/bigbang/bigbang.yaml
  config/jobs/ouzi-dev/cannon-prow/cannon-prow.yaml
  config/jobs/ouzi-dev/commit-status-updater/commit-status-updater.yaml
  config/jobs/ouzi-dev/credstash-operator/credstash_operator.yaml
  config/jobs/ouzi-dev/dind-action/dind-action.yaml
  config/jobs/ouzi-dev/docs/docs.yaml
  config/jobs/ouzi-dev/eks-terraform/eks-terraform.yaml
  config/jobs/ouzi-dev/gke-terraform/gke-terraform.yaml
  config/jobs/ouzi-dev/go-make-action/go-make-action.yaml
  config/jobs/ouzi-dev/hoarder-prow/hoarder-prow.yaml
  config/jobs/ouzi-dev/ouzi.io/ouzi-io.yaml
  config/jobs/ouzi-dev/owners-template/owners-template.yaml
  config/jobs/ouzi-dev/prow-gke-terraform/prow-gke-terraform.yaml
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts.yaml
  config/jobs/ouzi-dev/syrinx/syrinx.yaml
  config/jobs/ouzi-dev/test-infra/test-infra.yaml
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/M

#82 fix: credstash operator jobs
  config/jobs/ouzi-dev/credstash-operator/credstash_operator.yaml
Labels: approved, lgtm, size/M

#83 fix: silly change to trigger config rebuild
  config/jobs/ouzi-dev/credstash-operator/credstash_operator.yaml
Labels: approved, lgtm, size/XS

#84 fix: bring utility images in sync with helm chart
  prow/config.yaml
Labels: approved, lgtm, size/XS

#85 fix: trigger labels redeploy
  prow/labels.yaml
Labels: approved, lgtm, size/XS
