Repository ouzi-dev/test-infra, pull requests merged in 2020-07, with the labels that each got.

#117 fix: added setting for needs-retitle plugin
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, lgtm, size/M

#118 fix: enable needs-retitle in single repo for tests
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#119 fix: enable needs-retitle in all repos
  prow/labels.yaml
  prow/plugins.yaml
Labels: approved, lgtm, size/S

#120 fix: change need retitle label color
  prow/labels.yaml
Labels: approved, lgtm, size/XS

#121 fix: added needs-retitle default jobs
  config/jobs/ouzi-dev/needs-retitle/needs-retitle.yaml
Labels: approved, lgtm, size/M

#122 fix: retitle settings
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#123 fix: update prow installer
  cluster/Makefile
Labels: approved, lgtm, size/XS

#124 feat: remove deleted ouzi.io repo
  config/jobs/ouzi-dev/ouzi.io/ouzi-io.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#125 fix: updated prow chart
  cluster/Makefile
Labels: approved, lgtm, size/XS

#126 fix: added new commit type
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#127 fix: updated prow installer
  cluster/Makefile
Labels: approved, lgtm, size/XS

#128 feat: change to smaller instance type
  infrastructure/main.tf
  infrastructure/terraform.tfvars
  infrastructure/variables.tf
Labels: approved, lgtm, size/XS

#130 feat: update check config to prow version
  Makefile
  config/jobs/ouzi-dev/avro-kedavro/avro-kedavro.yaml
  config/jobs/ouzi-dev/bigbang/bigbang.yaml
  config/jobs/ouzi-dev/chart-museum-deploy/chart-museum-deploy.yaml
  config/jobs/ouzi-dev/claptrap/claptrap.yaml
  config/jobs/ouzi-dev/commit-status-updater/commit-status-updater.yaml
  config/jobs/ouzi-dev/credstash-operator/credstash_operator.yaml
  config/jobs/ouzi-dev/dind-action/dind-action.yaml
  config/jobs/ouzi-dev/docs/docs.yaml
  config/jobs/ouzi-dev/eks-terraform/eks-terraform.yaml
  config/jobs/ouzi-dev/gke-terraform/gke-terraform.yaml
  config/jobs/ouzi-dev/go-make-action/go-make-action.yaml
  config/jobs/ouzi-dev/hoarder-prow/hoarder-prow.yaml
  config/jobs/ouzi-dev/k8sprimitives1/k8sprimitives1.yaml
  config/jobs/ouzi-dev/needs-retitle/needs-retitle.yaml
  config/jobs/ouzi-dev/node-tagger/node-tagger.yaml
  config/jobs/ouzi-dev/owners-template/owners-template.yaml
  config/jobs/ouzi-dev/prow-gke-terraform/prow-gke-terraform.yaml
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts.yaml
  config/jobs/ouzi-dev/prow-installer/prow-installer.yaml
  config/jobs/ouzi-dev/syrinx/syrinx.yaml
  config/jobs/ouzi-dev/test-infra/test-infra.yaml
  config/jobs/ouzi-dev/whalers-of-the-moon/whalers_of_the_moon.yaml
Labels: approved, lgtm, size/M
