Repository ouzi-dev/test-infra, pull requests merged in 2020-03, with the labels that each got.

#86 feat: create node killer svc
  cluster/11-gke-preemptible-killer/manifests/pre/01-namespace.yaml
  cluster/11-gke-preemptible-killer/manifests/pre/02-rbac.yaml
  cluster/11-gke-preemptible-killer/manifests/pre/03-credstashsecret.yaml
  cluster/11-gke-preemptible-killer/manifests/pre/04-deployment.yaml
  cluster/11-gke-preemptible-killer/manifests_values.yaml.tpl
  cluster/12-gke-node-termination-handler/manifests/pre/01-rbac.yaml
  cluster/12-gke-node-termination-handler/manifests/pre/02-k8s.yaml
  cluster/12-gke-node-termination-handler/manifests_values.yaml.tpl
  cluster/Makefile
  cluster/values.yaml
  infrastructure/Makefile
  infrastructure/main.tf
  infrastructure/outputs.tf
  infrastructure/terraform.tfvars
  infrastructure/variables.tf
Labels: approved, lgtm, size/L

#87 feat: bring prow-installer under management
  prow/config.yaml
Labels: approved, lgtm, size/XS

#88 feat: add enforced prow installer jobs
  config/jobs/ouzi-dev/prow-installer/prow-installer.yaml
Labels: approved, lgtm, size/M

#90 feat: bump to latest toolbox
  config/jobs/ouzi-dev/test-infra/test-infra.yaml
Labels: approved, lgtm, size/S

#89 feat: add prow installer
  Makefile
  cluster/.gitignore
  cluster/00-storage/manifests/pre/ssd-retain.yaml
  cluster/00-storage/manifests_values.yaml.tpl
  cluster/01-rbac/manifests/pre/cluster_role_binding.yaml
  cluster/01-rbac/manifests_values.yaml.tpl
  cluster/02-pod-disruption-budget/manifests/pre/calico-node-autoscaler.yaml
  cluster/02-pod-disruption-budget/manifests/pre/calico-typha-autoscaler.yaml
  cluster/02-pod-disruption-budget/manifests/pre/calico-typha.yaml
  cluster/02-pod-disruption-budget/manifests/pre/event-exporter.yaml
  cluster/02-pod-disruption-budget/manifests/pre/fluentd-gcp-scaler.yaml
  cluster/02-pod-disruption-budget/manifests/pre/glbc.yaml
  cluster/02-pod-disruption-budget/manifests/pre/heapster.yaml
  cluster/02-pod-disruption-budget/manifests/pre/kube-dns-autoscaler.yaml
  cluster/02-pod-disruption-budget/manifests/pre/kube-dns.yaml
  cluster/02-pod-disruption-budget/manifests/pre/kubernetes-dashboard.yaml
  cluster/02-pod-disruption-budget/manifests/pre/metrics-server.yaml
  cluster/02-pod-disruption-budget/manifests_values.yaml.tpl
  cluster/04-cert-manager/helm_values.yaml.tpl
  cluster/04-cert-manager/manifests/crds/01-crds.yaml
  cluster/04-cert-manager/manifests/post/02-clouddns-dns01-solver-svc-acct.yaml
  cluster/04-cert-manager/manifests/post/03-cluster-issuer-letsencrypt.yaml
  cluster/04-cert-manager/manifests/pre/01-namespace.yaml
  cluster/04-cert-manager/manifests_values.yaml.tpl
  cluster/05-oauth-proxy/manifests/pre/01-namespace.yaml
  cluster/05-oauth-proxy/manifests/pre/02-secret.yaml
  cluster/05-oauth-proxy/manifests/pre/03-configmap.yaml
  cluster/05-oauth-proxy/manifests/pre/04-deployment.yaml
  cluster/05-oauth-proxy/manifests/pre/05-service.yaml
  cluster/05-oauth-proxy/manifests/pre/06-ingress.yaml
  cluster/05-oauth-proxy/manifests_values.yaml.tpl
  cluster/06-external-dns/helm_values.yaml.tpl
  cluster/06-external-dns/manifests/pre/01-namespace.yaml
  cluster/06-external-dns/manifests_values.yaml.tpl
  cluster/07-nginx-ingress/helm_values.yaml.tpl
  cluster/07-nginx-ingress/manifests/pre/01-namespace.yaml
  cluster/07-nginx-ingress/manifests_values.yaml.tpl
  cluster/08-prow/helm_values.yaml.tpl
  cluster/08-prow/manifests/pre/01-namespace-jobs.yaml
  cluster/08-prow/manifests/pre/01-namespace.yaml
  cluster/08-prow/manifests/pre/02-credstashsecret.yaml
  cluster/08-prow/manifests/pre/03-serviceaccount.yaml
  cluster/08-prow/manifests_values.yaml.tpl
  cluster/09-build-secrets/manifests/pre/00-credstashsecret.yaml
  cluster/09-build-secrets/manifests_values.yaml.tpl
  cluster/10-credstash-operator/helm_values.yaml.tpl
  cluster/10-credstash-operator/manifests/pre/01-namespace.yaml
  cluster/10-credstash-operator/manifests_values.yaml.tpl
  cluster/11-gke-preemptible-killer/manifests/pre/01-namespace.yaml
  cluster/11-gke-preemptible-killer/manifests/pre/02-rbac.yaml
  cluster/11-gke-preemptible-killer/manifests/pre/03-credstashsecret.yaml
  cluster/11-gke-preemptible-killer/manifests/pre/04-deployment.yaml
  cluster/11-gke-preemptible-killer/manifests_values.yaml.tpl
  cluster/12-gke-node-termination-handler/manifests/pre/01-rbac.yaml
  cluster/12-gke-node-termination-handler/manifests/pre/02-k8s.yaml
  cluster/12-gke-node-termination-handler/manifests_values.yaml.tpl
  cluster/Makefile
  cluster/values.yaml
  infrastructure/Makefile
  prow/config.yaml
Labels: approved, lgtm, size/XXL

#91 feat: remove old cannon repo
  config/jobs/ouzi-dev/cannon-prow/cannon-prow.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#92 feat: add surge support on node upgrades
  cluster/Makefile
  infrastructure/Makefile
  infrastructure/main.tf
Labels: approved, lgtm, size/XS

#93 fix: upgrade prow installer
  cluster/Makefile
  infrastructure/main.tf
  infrastructure/terraform.tfvars
  infrastructure/variables.tf
Labels: approved, lgtm, size/S

#94 fix: trigger a label config redeployment
  prow/labels.yaml
Labels: approved, lgtm, size/XS

#96 fix: bump toolbox
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts.yaml
  config/jobs/ouzi-dev/test-infra/test-infra.yaml
Labels: approved, lgtm, size/S

#95 feat: add kms ring and key for build secrets
  infrastructure/Makefile
  infrastructure/README.md
  infrastructure/main.tf
Labels: approved, lgtm, size/M

#97 feat: add svc for google cloud
  cluster/values.yaml
  infrastructure/Makefile
  infrastructure/outputs.tf
  prow/config.yaml
  prow/labels.yaml
Labels: approved, lgtm, size/M

#98 fix: rename gcloud prow svc preset
  prow/config.yaml
Labels: approved, lgtm, size/XS

#99 feat: upgrade prow installer
  cluster/Makefile
  cluster/values.yaml
Labels: approved, lgtm, size/M

#100 feat: add new repos under prow management
  config/jobs/ouzi-dev/claptrap/claptrap.yaml
  config/jobs/ouzi-dev/node-tagger/node-tagger.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#101 feat: delete prow helm chart jobs
  config/jobs/ouzi-dev/prow-helm-chart/prow-helm-charts.yaml
Labels: approved, lgtm, size/M
