Repository ouzi-dev/test-infra, pull requests merged in 2020-05, with the labels that each got.

#107 fix: switch to default renewal
  monitoring/manifests/expose/monitoring-certificate.yaml
Labels: approved, lgtm, size/XS

#108 feat: turn off auto provisioning
  infrastructure/main.tf
Labels: approved, lgtm, size/XS

#109 fix: cluster autoscaling default to off
  infrastructure/main.tf
Labels: approved, lgtm, size/XS

#110 feat: Add k8sprimitives1 repo
  config/jobs/ouzi-dev/k8sprimitives1/k8sprimitives1.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#111 fix: add piti
  prow/config.yaml
Labels: approved, lgtm, size/L

#112 feat: require branches to be up to date with base
  prow/config.yaml
Labels: approved, lgtm, size/M
