Repository ouzi-dev/test-infra, pull requests merged in 2020-06, with the labels that each got.

#113 Revert "feat: require branches to be up to date with base"
  prow/config.yaml
Labels: approved, lgtm, size/M

#114 feat: upgrade to prow installer v1.9.0 with prow v20200610-6c96a0a6ed
  cluster/Makefile
Labels: approved, lgtm, size/XS

#115 feat: add chart-museum-deploy to prow
  config/jobs/ouzi-dev/chart-museum-deploy/chart-museum-deploy.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#116 feat: add preset for pushing helm charts
  cluster/values.yaml
  prow/config.yaml
Labels: approved, lgtm, size/S
